[dev]
  command="pnpm start:webpack"
  targetPort=3000
  port=8888

[build]
  command="pnpm test && pnpm lint && pnpm build"
  publish="build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
